Updating Readmes I forgot to update.
avnet-iotconnect/iotc-yocto-c-sdk pull request #7
Opened 2023-08-08 13:40 UTC by vputys

2023-08-16 15:07 UTC, pywtk requested changes
great stuff! some changes requested & one query

2023-08-16 15:07 UTC, pywtk commented on board_specific_readmes/rpi4b.md
The instructions aren't as copy-pastable as they could be. With some refinements someone should be able to replicate the build quicker.

2023-08-16 15:07 UTC, pywtk commented on board_specific_readmes/rpi4b.md
> +    git clone git://git.yoctoproject.org/poky.git -b kirkstone
add " && \" to the end of all but the last of these lines so should an error occur the later lines do not execute.

2023-08-16 15:07 UTC, pywtk commented on board_specific_readmes/rpi4b.md
> +- Source work environment - `source <your_path>/poky/oe-init-build-env`
without being in a '```' comment block, this instruction doesn't benefit from the copy icon in the top right hand corner.

2023-08-16 15:07 UTC, pywtk commented on board_specific_readmes/rpi4b.md
> +- Source work environment - `source <your_path>/poky/oe-init-build-env`
by putting in the "<your-path>" users are going to have to edit every line they copy.

A different approach would be to suggest they make a working directory first & then assume every instruction executes from there.

2023-08-16 15:07 UTC, pywtk commented on board_specific_readmes/rpi4b.md
> +    <your_path>/meta-openembedded/meta-oe \
replace these with a single bitbake-layer call i.e. 

`bitbake-layers add-layer \
../meta-raspberrypi \
../meta-iotconnect \
../meta-myExampleIotconnectLayer`

2023-08-16 15:07 UTC, pywtk commented on board_specific_readmes/rpi4b.md
> +- Change `MACHINE` variable in `local.conf` file to `MACHINE = "raspberrypi4"`
change these to `echo -n "stuff" >> conf/local.conf`

2023-08-16 15:07 UTC, pywtk commented on board_specific_readmes/rpi4b.md
> +```
very interested to learn why these are required?

2023-08-16 15:07 UTC, pywtk commented on board_specific_readmes/rpi4b.md
> +- Add IoTC C SDK to your image (in your build image .bb file or in `local.conf`) - `IMAGE_INSTALL += " iotc-c-sdk"`
change to `echo`

2023-08-16 15:07 UTC, pywtk commented on board_specific_readmes/rpi4b.md
> +- Build your image - `bitbake <your_image>`
change to `core-image-minimal` or similar

2023-08-16 15:07 UTC, pywtk commented on board_specific_readmes/rpi4b.md
perhaps even putting this at the end as a "copy & paste & it should just work"


```
git clone git://git.yoctoproject.org/poky.git -b kirkstone && \
git clone git://git.openembedded.org/meta-openembedded  -b kirkstone && \
git clone git://git.yoctoproject.org/meta-raspberrypi.git -b kirkstone && \
wget https://github.com/vputys/iotc-yocto-c-sdk/archive/refs/heads/kirkstone.zip -O/tmp/tmp.zip && \
unzip /tmp/tmp.zip -d /tmp/ && \
mv /tmp/iotc-yocto-c-sdk-kirkstone/meta-* ../ && \
rm -r /tmp/tmp.zip /tmp/iotc-yocto-c-sdk-kirkstone && \
source poky/oe-init-build-env && \
bitbake-layers add-layer \
../meta-raspberrypi \
../meta-iotconnect \
../meta-myExampleIotconnectLayer && \
echo -n 'MACHINE="raspberrypi3"' >> conf/local.conf && \
echo -n 'INHERIT += "extrausers"
EXTRA_USERS_PARAMS = " useradd -p '\$5\$qjMzQ4sWI8S\$AJ/zzrYE2PJoyM9e6QLOV.L/xyDn0Lmk2E/aH4wd7o.' iot; \
                       usermod  -a -G sudo iot;"
IMAGE_INSTALL += " openssh"
IMAGE_INSTALL:append = " iotc-c-sdk"' >> conf/local.conf && \
bitbake core-image-minimal
```

2023-08-16 15:44 UTC, vputys commented on board_specific_readmes/rpi4b.md
> +```
me and Alen had problems with build/run without them

2023-08-21 15:20 UTC, pywtk approved these changes

2023-08-21 15:20 UTC, merged